version: 2.1
orbs:
  kustomize: finc/kustomize@0.0.2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: dezserv
          filters:
            branches:
              only: master
      - deploy:
          context: dezserv
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: circleci/node:latest
        auth:
          username: deznorth
          password: $DOCKERHUB_TOKEN
    environment:
      APP_NAME: 'bot-orion'
      DOCKER_REGISTRY: 'proget.deznorth.com/private-docker'
      REGISTRY_URL: 'proget.deznorth.com'
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: docker build -t deznorth/$APP_NAME:$CIRCLE_SHA1 .
      - run: docker tag deznorth/$APP_NAME:$CIRCLE_SHA1 $DOCKER_REGISTRY/deznorth/$APP_NAME:$CIRCLE_SHA1
      - run: docker login -u $PROGET_USER -p $PROGET_PASS $REGISTRY_URL # User and Pass from dezserv context
      - run: docker push $DOCKER_REGISTRY/deznorth/$APP_NAME:$CIRCLE_SHA1
  deploy:
    docker:
      - image: circleci/node:latest
        auth:
          username: deznorth
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - kustomize/install
      # - run:
      #     name: Fetch deployment manifest
      #     command: curl -H "$GITHUB_AUTH_HEADER" -o ./deployment.yaml -L https://raw.githubusercontent.com/deznorth/dezserv/master/Apps/Bot_Orion/deployment.yaml
      - run: git clone https://e271545d13a7a3a06332cc55a7d5cc27a5d7e68b@github.com/deznorth/dezserv.git
      - run: ls
      - run: cd dezserv/DezApps/Orion
      - run: ls
      - run: cat ./deployment.yaml
      - run: kustomize edit set image proget.deznorth.com/private-docker/deznorth/bot-orion:$CIRCLE_SHA1
      - run: cat ./deployment.yaml
