version: 2.1
orbs:
  kubernetes: circleci/kubernetes@0.11.2
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          context: dezserv
          filters:
            branches:
              only: master
      - deploy:
          context: dezserv
          requires:
            - build
          filters:
            branches:
              only: master
jobs:
  build:
    docker:
      - image: circleci/node:latest
        auth:
          username: deznorth
          password: $DOCKERHUB_TOKEN
    environment:
      APP_NAME: 'bot-orion'
      DOCKER_REGISTRY: 'proget.deznorth.com/private-docker'
      REGISTRY_URL: 'proget.deznorth.com'
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}
      - run: docker build -t deznorth/$APP_NAME:$CIRCLE_SHA1 .
      - run: docker tag deznorth/$APP_NAME:$CIRCLE_SHA1 $DOCKER_REGISTRY/deznorth/$APP_NAME:$CIRCLE_SHA1
      - run: docker login -u $PROGET_USER -p $PROGET_PASS $REGISTRY_URL # User and Pass from dezserv context
      - run: docker push $DOCKER_REGISTRY/deznorth/$APP_NAME:$CIRCLE_SHA1
  deploy:
    docker:
      - image: circleci/node:latest
        auth:
          username: deznorth
          password: $DOCKERHUB_TOKEN
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Configure Github Identity
          command: git config --global user.email $GITHUB_MACHINE_EMAIL && git config --global user.name $GITHUB_MACHINE_NAME
      - run: git clone git@github.com:deznorth/dezserv.git
      - run:
          name: update deployment manifest image
          command: cd ./dezserv/DezApps/Orion && kubectl patch --local -f deployment.yaml -p '{"spec":{"template":{"spec":{"containers":[{"name":"orion-bot","image":"proget.deznorth.com/private-docker/deznorth/bot-orion:$CIRCLE_SHA1"}]}}}}' -o yaml
      - run:
          name: commit changes
          command: cd ./dezserv && git add . && git commit -m "deploy bot-orion:$CIRCLE_SHA1"
      - run:
          name: push changes
          command: cd ./dezserv && git push
